### ISSUE TITLE
[Apple Silicon Mac] wrong evaluation when book ends

### ISSUE THREAD

**Issue by sensuikan1973** [sensuikan1973/pedax#1328]
From [Mac App Store](https://apps.apple.com/jp/app/pedax/id1557500142?mt=12) Review,

> Book が終わってからの挙動がおかしい
> edax の book は level 24, depth 36 で作成しています．
> 
> book で進行している限りは評価値などの表示も正常なのですが，book が終わった途端に，例えばその手の前まで 0 の評価値だったものが，すべての差し手が 64 のような評価値で表示されます．
> 
> pedax も level は 24 に設定しているので，book が終わった時点で完全読みになって book と同じ評価値の手が表示されないとおかしいはずなのですが…
> 
> それ以外はインターフェースもシンプルで見やすいので，余計に終盤の挙動が惜しいです．
> 
> この不具合（？）が直れば★5 をつけたいくらいです．

---

**There is a workaround. See: https://github.com/sensuikan1973/pedax/issues/1328#issuecomment-1461678071**

**Comment by sensuikan1973** [comment]
On my iMac, this issue can't be reproduce....

## system info
<img width="244" alt="image" src="https://user-images.githubusercontent.com/23427957/223603623-c6525da4-c173-49b5-86e8-c342669bad74.png">

## pedax local info
(command + L)

<img width="400" alt="image" src="https://user-images.githubusercontent.com/23427957/223603905-6cc2d4bc-9f8b-4c8d-8a0c-4a3e6ee29aa1.png">

```json
{
    "app": {
        "name": "pedax",
        "version": "3.1.0",
        "buildNumber": "82"
    },
    "config": {
        "bestpathCountAvailabilityOption": false,
        "bestpathCountPlayerLowerLimitOption": 128,
        "bestpathCountOpponentLowerLimitOption": 128,
        "hintStepByStepOption": false,
        "bookFileOption": "/Users/shimizunaoki/Downloads/saji_book.dat",
        "evalFileOption": "/Users/shimizunaoki/Library/Containers/com.done.sensuikan1973.pedax/Data/Documents/eval.dat",
        "levelOption": 24,
        "nTasksOption": 4
    },
    "system": {
        "numberOfProcessors": 16,
        "operatingSystemVersion": "バージョン13.2.1（ビルド22D68）"
    },
    "board": {
        "modeName": "freePlay",
        "currentMovesWithoutPassString": "",
        "bookHasBeenLoaded": true,
        "positionFullNum": 38604800,
        "hintsWithStepByStep": [
            {
                "isLastStep": "true",
                "hint.moveString": "d3",
                "hint.scoreString": "0",
                "hint.isBookMove": "true",
                "hint.depth": "0"
            },
            {
                "isLastStep": "true",
                "hint.moveString": "c4",
                "hint.scoreString": "0",
                "hint.isBookMove": "true",
                "hint.depth": "0"
            },
            {
                "isLastStep": "true",
                "hint.moveString": "f5",
                "hint.scoreString": "0",
                "hint.isBookMove": "true",
                "hint.depth": "0"
            },
            {
                "isLastStep": "true",
                "hint.moveString": "e6",
                "hint.scoreString": "0",
                "hint.isBookMove": "true",
                "hint.depth": "0"
            }
        ]
    }
}
```

**Comment by layla777** [comment]
Here's screenshots and info. Hope this helps.
<img width="392" alt="Screenshot 2023-03-09 at 3 00 10" src="https://user-images.githubusercontent.com/30713195/223793226-7f5c4018-0ce4-44a4-bb44-f568cd7ebca4.png">
<img width="912" alt="Screenshot 2023-03-09 at 2 58 25" src="https://user-images.githubusercontent.com/30713195/223793266-0f4ae916-1d98-47b4-a66f-4678e535d45d.png">
<img width="912" alt="Screenshot 2023-03-09 at 2 59 48" src="https://user-images.githubusercontent.com/30713195/223793317-4e28e0b7-8c65-4201-a7f7-96acc243cbbc.png">
{
	"app": {
		"name": "pedax",
		"version": "3.2.0",
		"buildNumber": "83"
	},
	"config": {
		"bestpathCountAvailabilityOption": true,
		"bestpathCountPlayerLowerLimitOption": 128,
		"bestpathCountOpponentLowerLimitOption": 128,
		"hintStepByStepOption": true,
		"bookFileOption": "/Users/layla/Projects/edax-reversi/bin/data/book.dat",
		"evalFileOption": "/Users/layla/Library/Containers/com.done.sensuikan1973.pedax/Data/Documents/eval.dat",
		"levelOption": 24,
		"nTasksOption": 2
	},
	"system": {
		"numberOfProcessors": 8,
		"operatingSystemVersion": "Version 13.2.1 (Build 22D68)"
	},
	"board": {
		"modeName": "freePlay",
		"currentMovesWithoutPassString": "",
		"bookHasBeenLoaded": true,
		"positionFullNum": 11400136,
		"hintsWithStepByStep": [
			{
				"isLastStep": "true",
				"hint.moveString": "d3",
				"hint.scoreString": "0",
				"hint.isBookMove": "true",
				"hint.depth": "0"
			},
			{
				"isLastStep": "true",
				"hint.moveString": "c4",
				"hint.scoreString": "0",
				"hint.isBookMove": "true",
				"hint.depth": "0"
			},
			{
				"isLastStep": "true",
				"hint.moveString": "f5",
				"hint.scoreString": "0",
				"hint.isBookMove": "true",
				"hint.depth": "0"
			},
			{
				"isLastStep": "true",
				"hint.moveString": "e6",
				"hint.scoreString": "0",
				"hint.isBookMove": "true",
				"hint.depth": "0"
			}
		]
	}
}

**Comment by layla777** [comment]
edax itself seems to be working without problem.

```
  A B C D E F G H            BLACK            A  B  C  D  E  F  G  H
1 - - - - - - - - 1         0:00.000       1 |  |  |  |  |  |  |  |  | 1
2 - - - - - - - - 2    2 discs   4 moves   2 |  |  |  |  |  |  |  |  | 2
3 - - - . - - - - 3                        3 |  |  |  |  |  |  |  |  | 3
4 - - . O * - - - 4  ply  1 (60 empties)   4 |  |  |  |()|##|  |  |  | 4
5 - - - * O . - - 5    Black's turn (*)    5 |  |  |  |##|()|  |  |  | 5
6 - - - - . - - - 6                        6 |  |  |  |  |  |  |  |  | 6
7 - - - - - - - - 7    2 discs   4 moves   7 |  |  |  |  |  |  |  |  | 7
8 - - - - - - - - 8         0:00.000       8 |  |  |  |  |  |  |  |  | 8
  A B C D E F G H            WHITE            A  B  C  D  E  F  G  H

>play F5f6E6d6E7g5C5c6E3d3C7f3F4g4H5h4D7g6F7e8H3f8G3h6D8c8H7b4B5b8C4b3A3a5A4a2D2


  A B C D E F G H            BLACK            A  B  C  D  E  F  G  H
1 - - - . - - - - 1         0:04.545       1 |  |  |  |  |  |  |  |  | 1
2 O - - * . . - . 2   22 discs   8 moves   2 |36|  |  |37|  |  |  |  | 2
3 O O . * * O * * 3                        3 |33|32|  |10| 9|12|23|21| 3
4 O * O * * * * * 4  ply 38 (23 empties)   4 |35|28|31|()|##|13|14|16| 4
5 O * O O * * * * 5    White's turn (O)    5 |34|29| 7|##|()| 1| 6|15| 5
6 . . * O O * * * 6                        6 |  |  | 8| 4| 3| 2|18|24| 6
7 - . O * O O - * 7   19 discs   8 moves   7 |  |  |11|17| 5|19|  |27| 7
8 - O O O O O - - 8         0:00.000       8 |  |30|26|25|20|22|  |  | 8
  A B C D E F G H            WHITE            A  B  C  D  E  F  G  H

>hint 10

 depth|score|       time   |  nodes (N)  |   N/s    | principal variation
------+-----+--------------+-------------+----------+----------------------
   23   +00        0:02.672      95116042   35597321 E2 b6 C3 c2 D1 f2 F1 e1 C1
   23   -02        0:00.003         22270    7423333 A6 b6 E2 c2 C3 b7 G7 f1 E1
   23   -06        0:00.001         18782   18782000 F2 c3 C2 e1 G1 f1 E2 h1 G2
   23   -06        0:00.001         15180   15180000 C3 b6 A6 c2 E2 b7 E1 b2 D1
   23   -10        0:00.001         12252   12252000 D1 c3 E2 f1 E1 c1 A6 b6 B2
   23   -16        0:00.000          8882            B6 e2 F2 c3 B2 e1 C2 b1 G1
   23   -16        0:00.001          5919    5919000 B7 a8 F2 c3 D1 c2 A6 a7 B2
   23   -24        0:00.000          2388            H2 h1 A6 c3 B6 e2 F2 g7 C1
------+-----+--------------+-------------+----------+----------------------

```

**Comment by layla777** [comment]
@sensuikan1973 
Here they are.

```
{
    "app": {
        "name": "pedax",
        "version": "3.2.0",
        "buildNumber": "83"
    },
    "config": {
        "bestpathCountAvailabilityOption": false,
        "bestpathCountPlayerLowerLimitOption": 128,
        "bestpathCountOpponentLowerLimitOption": 128,
        "hintStepByStepOption": true,
        "bookFileOption": "/Users/layla/Projects/edax-reversi/bin/data/book.dat",
        "evalFileOption": "/Users/layla/Library/Containers/com.done.sensuikan1973.pedax/Data/Documents/eval.dat",
        "levelOption": 24,
        "nTasksOption": 2
    },
    "system": {
        "numberOfProcessors": 8,
        "operatingSystemVersion": "Version 13.2.1 (Build 22D68)"
    },
    "board": {
        "modeName": "freePlay",
        "currentMovesWithoutPassString": "F5f6E6d6E7g5C5c6E3d3C7f3F4g4H5h4D7g6F7e8H3f8G3h6D8c8H7b4B5b8C4b3A3a5A4a2D2",
        "bookHasBeenLoaded": true,
        "positionFullNum": 0,
        "hintsWithStepByStep": [
            {
                "isLastStep": "false",
                "hint.moveString": "a6",
                "hint.scoreString": "+64",
                "hint.isBookMove": "false",
                "hint.depth": "23"
            },
            {
                "isLastStep": "false",
                "hint.moveString": "e2",
                "hint.scoreString": "+64",
                "hint.isBookMove": "false",
                "hint.depth": "23"
            },
            {
                "isLastStep": "false",
                "hint.moveString": "d1",
                "hint.scoreString": "+64",
                "hint.isBookMove": "false",
                "hint.depth": "23"
            },
            {
                "isLastStep": "false",
                "hint.moveString": "c3",
                "hint.scoreString": "+64",
                "hint.isBookMove": "false",
                "hint.depth": "23"
            }
        ]
    }
}

```
<img width="868" alt="Screenshot 2023-03-09 at 10 46 22" src="https://user-images.githubusercontent.com/30713195/223894890-4dac509b-6bfe-4ef5-80c2-0112dad18c89.png">
<img width="868" alt="Screenshot 2023-03-09 at 10 52 16" src="https://user-images.githubusercontent.com/30713195/223895108-5191ca65-6c13-41a1-b496-896a1d837742.png">

**Comment by sensuikan1973** [comment]
Thank you very much. I'll investigate into this issue tsome weekend in March.

**Comment by sensuikan1973** [comment]
in https://github.com/sensuikan1973/pedax/issues/1328#issuecomment-1461148340 , It's strane that `hintsWithStepByStep` size doesn't match real hint number, and all hintWithStepByStep have **false** `isLastStep`.

hum... 
I asked my M1 Mac friend and he confirmed the same issue, so the cpu architecture may have an effect.

**Comment by layla777** [comment]
Thank you! It worked.

For now, I'm satisfied with this workaround. Thanks again!

**Comment by sensuikan1973** [comment]
https://github.com/sensuikan1973/pedax/pull/1396 resolved this issue.
https://github.com/sensuikan1973/pedax/pull/1398 removed unnecessary annotation.

And, I'll publish new version to App Storet in a few days.
