### ISSUE TITLE
windows msix packaging is stucked

### ISSUE THREAD

**Issue by sensuikan1973** [sensuikan1973/pedax#1467]
https://github.com/YehudaKremer/msix/issues/193#issuecomment-1543704779

**Comment by YehudaKremer** [comment]
please try https://github.com/YehudaKremer/msix/issues/193#issuecomment-1543773465 on your CI

**Comment by sensuikan1973** [comment]
debug https://github.com/sensuikan1973/pedax/pull/1468

**Comment by YehudaKremer** [comment]
Hello again @sensuikan1973 

Please try the new version (3.12.0) https://github.com/YehudaKremer/msix/issues/193#issuecomment-1544145638

**Comment by sensuikan1973** [comment]
https://github.com/sensuikan1973/pedax/pull/1469#issuecomment-1544211298
