### ISSUE TITLE
Does this inherit the same behaviour of the original Edax in not completing long search?

### ISSUE THREAD

**Issue by chunglimlee** [sensuikan1973/pedax#2306]
Does this program inherit the following from original Edax?

Edax has a tendency to not 100% finish search ahead of certain plys.

For example, after 20 moves, search ply 40 will not even give you the option to actually solve it with indefinite time, but it just gives a 73% or something percentage (using "level 40" and hint "1").   It seems to have an auto cut off time to complete a search on its own.

**Comment by sensuikan1973** [comment]
yes
